import logging
from datetime import datetime
from typing import Dict, Any

logger = logging.getLogger("OSINT_Tool")


def generate_markdown_report(results: Dict[str, Any], output_file: str):
    """
    Generate a clean Markdown report with tiered results.
    
    Args:
        results: Results dictionary
        output_file: Output file path
    """
    logger.info(f"Generating Markdown report: {output_file}")
    
    target = results.get('target', 'Unknown')
    target_type = results.get('target_type', 'Unknown')
    
    md_content = []
    
    # Header
    md_content.append(f"# OSINT Report: {target}")
    md_content.append(f"\n**Target Type:** {target_type}")
    md_content.append(f"\n**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    md_content.append("\n---\n")
    
    # Statistics
    if 'statistics' in results:
        stats = results['statistics']
        md_content.append("## 📊 Summary Statistics\n")
        md_content.append(f"- **Total Results:** {stats.get('total_unique', 0)}")
        md_content.append(f"- **Confirmed Findings:** {stats.get('confirmed_count', 0)}")
        md_content.append(f"- **Possible Findings:** {stats.get('possible_count', 0)}\n")
    
    # Email Enumeration
    if 'emails' in results and results['emails']:
        emails_data = results['emails']
        confirmed = emails_data.get('confirmed_emails', [])
        possible = emails_data.get('possible_emails', [])
        
        md_content.append("## 📧 Email Intelligence\n")
        
        if confirmed:
            md_content.append("### ✅ Confirmed Emails\n")
            md_content.append("| Email | Source | Confidence |")
            md_content.append("|-------|--------|------------|")
            for item in confirmed:
                email = item.get('email', 'Unknown')
                source = item.get('source', 'Unknown')
                conf = item.get('confidence', 1.0)
                md_content.append(f"| {email} | {source} | {int(conf*100)}% |")
            md_content.append("")
            
        if possible:
            md_content.append("### ⚠️ Possible Emails\n")
            md_content.append("| Email | Source | Confidence |")
            md_content.append("|-------|--------|------------|")
            for item in possible[:20]:
                email = item.get('email', 'Unknown')
                source = item.get('source', 'Pattern')
                conf = item.get('confidence', 0.5)
                md_content.append(f"| {email} | {source} | {int(conf*100)}% |")
            if len(possible) > 20:
                md_content.append(f"\n*...and {len(possible)-20} more*")
            md_content.append("")
    
    # Social Media
    social_media = results.get('social_media', [])
    if social_media:
        md_content.append("## 👥 Social Media Profiles\n")
        md_content.append("| Platform | URL | Source | Confidence |")
        md_content.append("|----------|-----|--------|------------|")
        
        for profile in social_media:
            platform = profile.get('platform', 'N/A')
            url = profile.get('url', 'N/A')
            source = profile.get('source', 'Unknown')
            conf = profile.get('confidence', 0.0)
            md_content.append(f"| {platform} | {url} | {source} | {int(conf*100)}% |")
        
        md_content.append("")
    
    # Footer
    md_content.append("\n---")
    md_content.append("\n*Generated by Hermes OSINT Tool v1.3*")
    
    # Write to file
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(md_content))
    
    logger.info(f"✓ Markdown report saved to {output_file}")
