import logging
from datetime import datetime
from typing import Dict, Any, List

logger = logging.getLogger("OSINT_Tool")


def generate_markdown_report(results: Dict[str, Any], output_file: str):
    """
    Generate a clean Markdown report.
    
    Args:
        results: Results dictionary
        output_file: Output file path
    """
    logger.info(f"Generating Markdown report: {output_file}")
    
    target = results.get('target', 'Unknown')
    target_type = results.get('target_type', 'Unknown')
    
    md_content = []
    
    # Header
    md_content.append(f"# OSINT Report: {target}")
    md_content.append(f"\n**Target Type:** {target_type}")
    md_content.append(f"\n**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    md_content.append("\n---\n")
    
    # Statistics
    if 'statistics' in results:
        stats = results['statistics']
        md_content.append("## 📊 Summary Statistics\n")
        md_content.append(f"- **Total Results:** {stats.get('total_unique', 0)}")
        md_content.append(f"- **Duplicates Removed:** {stats.get('duplicates_removed', 0)}")
        md_content.append(f"- **Average Quality Score:** {stats.get('avg_quality_score', 0):.1f}/100")
        md_content.append(f"- **High Quality Results:** {stats.get('high_quality_results', 0)}")
        md_content.append(f"- **Connections Found:** {stats.get('connections_found', 0)}\n")
    
    # Email Enumeration
    if 'emails' in results and results['emails']:
        emails = results['emails']
        md_content.append("## 📧 Email Enumeration\n")
        md_content.append(f"**Generated:** {emails.get('valid_format_count', 0)} potential email addresses\n")
        
        if emails.get('emails_generated'):
            md_content.append("### Email Addresses\n")
            for email in emails['emails_generated'][:20]:  # Limit to 20
                md_content.append(f"- `{email}`")
            md_content.append("")
        
        if emails.get('domains_with_mx'):
            md_content.append(f"**Domains with MX Records:** {', '.join(emails['domains_with_mx'])}\n")
    
    # Social Media
    social_media = results.get('social_media', [])
    if social_media:
        md_content.append("## 👥 Social Media Profiles\n")
        md_content.append("| Platform | Status | URL | Quality Score |")
        md_content.append("|----------|--------|-----|---------------|")
        
        for profile in social_media:
            platform = profile.get('platform', 'N/A')
            status = profile.get('status', 'N/A')
            url = profile.get('url', 'N/A')
            score = profile.get('quality_score', 0)
            md_content.append(f"| {platform} | {status} | {url} | {score}/100 |")
        
        md_content.append("")
    
    # Search Results
    search_results = results.get('search_engines', [])
    if search_results:
        md_content.append("## 🔍 Search Engine Results\n")
        md_content.append("| Source | Title | URL | Quality Score |")
        md_content.append("|--------|-------|-----|---------------|")
        
        for result in search_results[:20]:  # Limit to 20
            source = result.get('source', 'N/A')
            title = result.get('title', 'N/A')[:50]  # Truncate long titles
            url = result.get('url', 'N/A')
            score = result.get('quality_score', 0)
            md_content.append(f"| {source} | {title} | {url} | {score}/100 |")
        
        md_content.append("")
    
    # Connections
    connections = results.get('connections', [])
    if connections:
        md_content.append("## 🔗 Connections\n")
        for conn in connections:
            conn_type = conn.get('type', 'Unknown')
            description = conn.get('description', '')
            md_content.append(f"- **{conn_type}**: {description}")
        md_content.append("")
    
    # Footer
    md_content.append("\n---")
    md_content.append("\n*Generated by OSINT Tool*")
    
    # Write to file
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(md_content))
    
    logger.info(f"✓ Markdown report saved to {output_file}")
